import { CABINET_FINISHES } from './catalogs';
import { createIsland, updateCountertop, updateIsland } from './countertops';
import { generateDesigns } from './design';
import { EditorObject, EditorProject, isCabinetKind, objectDefaults } from './editor';

export type AILayoutType = 'Single Wall'|'L-Shape'|'Galley'|'U-Shape';
export type AIDesignSuggestion = {
  id: string;
  name: string;
  description: string;
  layout: AILayoutType;
  style: 'warm'|'modern'|'classic';
  includesIsland: boolean;
};

const inches=(meters:number)=>meters*39.3701;
const cabinetFinishForStyle=(style:AIDesignSuggestion['style'])=>{
  const target=style==='warm'?'White Oak':style==='modern'?'Warm White':'Navy';
  return CABINET_FINISHES.find(item=>item.name===target)??CABINET_FINISHES[0];
};

export function aiDesignSuggestions(project:EditorProject):AIDesignSuggestion[]{
  const base=generateDesigns(project.room);
  const width=inches(project.room.widthM),length=inches(project.room.lengthM);
  const layouts:AILayoutType[] = width>=132&&length>=144?['L-Shape','U-Shape','Galley']:width>=108?['L-Shape','Galley','Single Wall']:['Single Wall','L-Shape','Galley'];
  return base.map((design,index)=>({id:`ai-${design.style}-${layouts[index]}`,name:`${layouts[index]} · ${design.name}`,description:design.description,layout:layouts[index],style:design.style,includesIsland:design.includesIsland&&layouts[index]!=='Galley'}));
}

const cabinet=(kind:EditorObject['kind'],id:string,name:string,x:number,y:number,widthIn:number,rotation=0)=>objectDefaults(kind,{id,name,x,y,widthIn,rotation});
function row(startX:number,startY:number,totalWidth:number,prefix:string,rotation=0):EditorObject[]{
  const widths=[24,30,36,24,30,36];
  const objects:EditorObject[]=[]; let cursor=0,index=0;
  while(cursor<totalWidth-18&&index<10){const width=Math.min(widths[index%widths.length],Math.max(18,totalWidth-cursor));objects.push(cabinet(index===1?'drawer-base':index===2?'sink-base':'base-cabinet',`${prefix}-base-${index}`,index===2?'Sink Base':index===1?'Drawer Base':'Base Cabinet',startX+(rotation===90?0:cursor),startY+(rotation===90?cursor:0),width,rotation));objects.push(objectDefaults('wall-cabinet',{id:`${prefix}-upper-${index}`,name:'Wall Cabinet',x:startX+(rotation===90?0:cursor),y:startY+(rotation===90?cursor:0),widthIn:width,rotation}));cursor+=width;index++;}
  return objects;
}

export function applyAIDesignSuggestion(project:EditorProject,suggestion:AIDesignSuggestion):EditorProject{
  // Preserve architectural shell and user openings. Replace only cabinetry/island/counters/appliances generated by the editor.
  const preserved=project.objects.filter(object=>object.kind==='wall'||object.kind==='door'||object.kind==='window'||(!isCabinetKind(object.kind)&&object.kind!=='island'&&object.kind!=='countertop'&&object.kind!=='appliance'));
  const roomWidth=Math.max(96,inches(project.room.widthM)),roomLength=Math.max(96,inches(project.room.lengthM));
  const runX=Math.min(roomWidth-24,144),runY=Math.min(roomLength-24,132);
  let generated:EditorObject[]=[];
  if(suggestion.layout==='Single Wall')generated.push(...row(120,120,runX,'ai-north'));
  if(suggestion.layout==='L-Shape'){generated.push(...row(120,120,runX,'ai-north'));generated.push(...row(120,150,Math.max(60,runY-36),'ai-west',90));}
  if(suggestion.layout==='Galley'){generated.push(...row(120,120,runX,'ai-galley-a'));generated.push(...row(120,240,runX,'ai-galley-b'));}
  if(suggestion.layout==='U-Shape'){generated.push(...row(120,120,runX,'ai-north'));generated.push(...row(120,150,Math.max(60,runY-36),'ai-west',90));generated.push(...row(120+runX,150,Math.max(60,runY-36),'ai-east',90));}
  const finish=cabinetFinishForStyle(suggestion.style);
  generated=generated.map(object=>isCabinetKind(object.kind)?{...object,color:finish.baseColor,finishId:finish.id,toeKick:object.toeKick?{...object.toeKick,color:finish.baseColor,finish:finish.finishType}:object.toeKick}:object);
  let next:EditorProject={...project,design:{...project.design,style:suggestion.style,cabinetColor:suggestion.style==='warm'?'wood':suggestion.style==='modern'?'white':'navy',includesIsland:suggestion.includesIsland},objects:[...preserved,...generated],selectedId:undefined,updatedAt:new Date().toISOString()};
  if(suggestion.includesIsland){const island=createIsland({id:'ai-island',name:'AI Island',x:250,y:245,widthIn:Math.min(84,Math.max(60,roomWidth*.42)),depthIn:42,color:finish.baseColor,finishId:finish.id});next={...next,objects:[...next.objects,island],selectedId:island.id};next=updateIsland(next,island.id,{seatingCount:3,sink:suggestion.style!=='classic',dishwasher:suggestion.style!=='classic'});next=updateCountertop(next,island.id,{materialId:suggestion.style==='classic'?'quartz-calacatta':'quartz-white'});}
  return next;
}
