export type WallPaint = { id: string; name: string; displayName: string; approximateHex: string; category: string; brandReference?: string; favorite: boolean; recent: boolean; applicableTo: 'wall'[] };
export type CabinetFinish = { id: string; name: string; displayName: string; baseColor: string; category: 'painted' | 'wood'; finishType: string; roughness: number; metalness: number; favorite: boolean; recent: boolean; grainDirection?: 'horizontal' | 'vertical' };
export type HardwareFinish = { id: string; name: string; displayName: string; baseColor: string; metalness: number; roughness: number; category: 'metal' | 'paint' | 'glass' | 'wood'; favorite: boolean; marketCommon: boolean };

const wall = (name: string, approximateHex: string, category: string, brandReference?: string): WallPaint => ({ id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'), name, displayName: name, approximateHex, category, brandReference, favorite: false, recent: false, applicableTo: ['wall'] });
export const WALL_PAINTS: WallPaint[] = [
  wall('Pure White', '#F4F1E8', 'Neutrals & Whites', 'Sherwin-Williams reference'), wall('Extra White', '#F7F7F3', 'Neutrals & Whites', 'Sherwin-Williams reference'), wall('Alabaster', '#EDEAE0', 'Neutrals & Whites', 'Sherwin-Williams reference'), wall('Snowbound', '#EDEAE4', 'Neutrals & Whites'), wall('Shoji White', '#E6DFD2', 'Neutrals & Whites'), wall('Creamy', '#EEE7D5', 'Neutrals & Whites'), wall('Greek Villa', '#F0EBDF', 'Neutrals & Whites'), wall('White Dove', '#ECEAE0', 'Neutrals & Whites'), wall('Swiss Coffee', '#EEE9DC', 'Neutrals & Whites'),
  wall('Accessible Beige', '#D1C5B4', 'Beige & Greige'), wall('Agreeable Gray', '#D0C7B8', 'Beige & Greige'), wall('Revere Pewter', '#CCC7BA', 'Beige & Greige'), wall('Edgecomb Gray', '#D4CEC0', 'Beige & Greige'), wall('Pale Oak', '#D9D2C6', 'Beige & Greige'), wall('Natural Linen', '#D8C9B5', 'Beige & Greige'),
  wall('Repose Gray', '#C9C5BD', 'Grays'), wall('Light French Gray', '#C8C7C0', 'Grays'), wall('Mindful Gray', '#B8B2A8', 'Grays'), wall('Dorian Gray', '#A9A39B', 'Grays'), wall('Gauntlet Gray', '#78736D', 'Grays'), wall('Peppercorn', '#5C5A57', 'Grays'),
  wall('Tricorn Black', '#2B2B2A', 'Dark Colors'), wall('Iron Ore', '#434341', 'Dark Colors'), wall('Urbane Bronze', '#565049', 'Dark Colors'), wall('Charcoal', '#454749', 'Dark Colors'),
  wall('Naval', '#2F3D4C', 'Blues'), wall('Hale Navy', '#344452', 'Blues'), wall('Smoky Blue', '#607888', 'Blues'), wall('Blue Gray', '#81909A', 'Blues'),
  wall('Evergreen Fog', '#959A88', 'Greens'), wall('Sea Salt', '#CDD6CB', 'Greens'), wall('Sage Green', '#9EA68F', 'Greens'), wall('Olive Green', '#777A55', 'Greens'), wall('Forest Green', '#3C5543', 'Greens'),
];

const cabinet = (name: string, baseColor: string, category: 'painted' | 'wood', finishType = 'Satin', roughness = 0.48): CabinetFinish => ({ id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'), name, displayName: name, baseColor, category, finishType, roughness, metalness: 0, favorite: false, recent: false, grainDirection: category === 'wood' ? 'vertical' : undefined });
export const CABINET_FINISHES: CabinetFinish[] = [
  ...[['Bright White','#FAFAF7'],['Pure White','#F4F1E8'],['Warm White','#EFE9DC'],['Cream','#E9DFC9'],['Ivory','#E5D7BE'],['Greige','#C9C0B2'],['Light Gray','#CDD0CE'],['Medium Gray','#969A99'],['Charcoal','#515657'],['Black','#282B2B'],['Navy','#334B62'],['Blue Gray','#71828D'],['Sage','#98A08C'],['Olive','#7A7D59'],['Forest Green','#3C5543'],['Deep Blue','#24445A'],['Terracotta','#B76E55']].map(([n,c]) => cabinet(n,c,'painted')),
  ...[['White Oak','#C9AD84'],['Natural Oak','#B98F5C'],['Red Oak','#A8774C'],['Rift Cut Oak','#B99263'],['Quarter Sawn Oak','#A98458'],['Natural Walnut','#79563F'],['Dark Walnut','#4E382D'],['Espresso Walnut','#352820'],['Maple','#D1B184'],['Natural Maple','#C8A575'],['Cherry','#9F6048'],['Hickory','#A7825C'],['Birch','#CCAD7E'],['Alder','#B8835A'],['Mahogany','#6B3E32'],['Espresso','#3E2E25'],['Driftwood','#978C7B'],['Weathered Wood','#837B70']].map(([n,c]) => cabinet(n,c,'wood','Natural',0.62)),
];
export const FINISH_TYPES = ['Matte','Satin','Semi-Gloss','Gloss','Natural','Stained','Painted','Distressed','Glazed','Textured'] as const;

const hardware = (name: string, baseColor: string, metalness = 1, roughness = .32, category: HardwareFinish['category'] = 'metal'): HardwareFinish => ({ id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'), name, displayName: name, baseColor, metalness, roughness, category, favorite: false, marketCommon: true });
export const HARDWARE_FINISHES: HardwareFinish[] = [
  hardware('Polished Chrome','#DDE2E5',1,.08), hardware('Brushed Chrome','#C4CDD0',1,.36), hardware('Satin Chrome','#BFC7C8',1,.44), hardware('Polished Nickel','#D4D1C7',1,.12), hardware('Brushed Nickel','#B8B3A9',1,.42), hardware('Satin Nickel','#AAA79E',1,.48), hardware('Stainless Steel','#AAB2B3',1,.34), hardware('Brushed Stainless Steel','#9FA7A8',1,.46),
  hardware('Matte Black','#1E2020',.15,.82,'paint'), hardware('Flat Black','#181919',.08,.92,'paint'), hardware('Soft Black','#2C2C2B',.12,.76,'paint'), hardware('Oil-Rubbed Bronze','#3F3028',.72,.55), hardware('Venetian Bronze','#544033',.78,.48), hardware('Dark Bronze','#4A3930',.8,.45), hardware('Champagne Bronze','#B79562',.9,.34), hardware('Brushed Brass','#B08A4F',.92,.42), hardware('Satin Brass','#B89758',.9,.48), hardware('Polished Brass','#C9A34B',.96,.12), hardware('Antique Brass','#8D6E3F',.86,.52), hardware('Aged Brass','#876B42',.84,.58), hardware('Unlacquered Brass','#B28A46',.9,.36), hardware('Copper','#B46B4E',.9,.32), hardware('Antique Copper','#875243',.84,.56), hardware('Rose Gold','#B77F78',.82,.35), hardware('Gunmetal','#515A5E',.9,.38), hardware('Pewter','#777A78',.75,.5), hardware('Graphite','#555A5B',.65,.6), hardware('White','#F2F2EF',.05,.7,'paint'), hardware('Ceramic White','#F7F5EE',.05,.58,'paint'), hardware('Clear Glass','#E9F4F6',.08,.05,'glass'), hardware('Crystal','#EEF8FB',.05,.02,'glass'), hardware('Wood','#8A5E3D',0,.68,'wood'),
];
export const HARDWARE_STYLES = ['Bar Pull','T-Bar Pull','Arch Pull','Cup Pull','Bail Pull','Finger Pull','Edge Pull','Tab Pull','Appliance Pull','Round Knob','Square Knob','Mushroom Knob','No Hardware'] as const;
export const HARDWARE_SIZES = ['3 inches','3 3/4 inches','5 inches','6 5/16 inches','7 9/16 inches','8 inches','10 inches','12 inches','Appliance Size','Custom Size'] as const;
export const HARDWARE_POSITIONS = ['Center','Upper Corner','Lower Corner','Vertical','Horizontal','Edge Mounted','Custom Position'] as const;
