import { countertopData, countertopMaterial, islandData } from './countertops';
import { EditorObject, isBaseCabinetKind, isBaseLikeKind, isCabinetKind } from './editor';
import { hardwareGeometry } from './hardwareGeometry';
import { isLighting, kelvinColor, lightingData } from './lighting';
import { openingData, openingsForWall } from './openings';

export type Box3D = {
  id:string; sourceId?:string;
  kind:'wall'|'cabinet'|'cabinet-door'|'countertop'|'toe-kick'|'hardware'|'opening'|'appliance'|'floor'|'trim'|'fixture'|'seating'|'lighting';
  center:[number,number,number]; size:[number,number,number]; rotationY:number; color:string; roughness:number; metalness:number;
};
const inchesToScene=(value:number)=>value/24;
const toRadians=(degrees:number)=>degrees*Math.PI/180;
const isBaseLike=(object:EditorObject)=>isBaseLikeKind(object.kind);
const isCabinet=(object:EditorObject)=>isCabinetKind(object.kind);

export type ToeKickRun={ids:string[];x:number;y:number;widthIn:number;depthIn:number;rotation:number;heightIn:number;recessIn:number;color:string};
export function continuousToeKickRuns(objects:EditorObject[],toleranceIn=2):ToeKickRun[]{const candidates=objects.filter(object=>isBaseLike(object)&&object.toeKick?.enabled),used=new Set<string>(),runs:ToeKickRun[]=[];for(const first of candidates){if(used.has(first.id))continue;const rotation=((first.rotation%360)+360)%360,horizontal=Math.abs(rotation%180)<1;const group=candidates.filter(object=>!used.has(object.id)&&Math.abs((((object.rotation%360)+360)%360)-rotation)<1).filter(object=>horizontal?Math.abs(object.y-first.y)<=toleranceIn:Math.abs(object.x-first.x)<=toleranceIn).sort((a,b)=>horizontal?a.x-b.x:a.y-b.y);let current:EditorObject[]=[];const flush=()=>{if(!current.length)return;current.forEach(object=>used.add(object.id));const start=current[0],end=current[current.length-1],startAxis=horizontal?start.x:start.y,endAxis=(horizontal?end.x:end.y)+end.widthIn,span=Math.max(start.widthIn,endAxis-startAxis);runs.push({ids:current.map(object=>object.id),x:horizontal?startAxis+span/2:start.x,y:horizontal?start.y:startAxis+span/2,widthIn:span,depthIn:Math.max(...current.map(object=>Math.max(1,object.depthIn-(object.toeKick?.recessIn??3)))),rotation,heightIn:Math.max(...current.map(object=>object.toeKick?.heightIn??4)),recessIn:Math.max(...current.map(object=>object.toeKick?.recessIn??3)),color:start.toeKick?.color??start.color??'#E8E3D8'});current=[];};for(const cabinet of group){if(!current.length){current.push(cabinet);continue;}const previous=current[current.length-1],previousEnd=(horizontal?previous.x:previous.y)+previous.widthIn,nextStart=horizontal?cabinet.x:cabinet.y;if(Math.abs(nextStart-previousEnd)<=toleranceIn)current.push(cabinet);else{flush();current.push(cabinet);}}flush();}return runs;}

function materialFor(object:EditorObject){const name=(object.material??'').toLowerCase(),finish=(object.finishId??'').toLowerCase(),metallic=name.includes('stainless')||name.includes('metal')||name.includes('chrome'),matte=finish.includes('matte'),gloss=finish.includes('gloss');return{metalness:metallic?.85:.04,roughness:matte?.82:gloss?.22:metallic?.3:.46};}
function wallPoint(wall:EditorObject,alongIn:number,depthIn=wall.depthIn/2){const radians=toRadians(wall.rotation);return{x:wall.x+Math.cos(radians)*alongIn-Math.sin(radians)*depthIn,z:wall.y+Math.sin(radians)*alongIn+Math.cos(radians)*depthIn};}
function addWallSegment(boxes:Box3D[],wall:EditorObject,id:string,startIn:number,lengthIn:number,bottomIn:number,heightIn:number){if(lengthIn<=.05||heightIn<=.05)return;const point=wallPoint(wall,startIn+lengthIn/2);boxes.push({id,sourceId:wall.id,kind:'wall',center:[inchesToScene(point.x),inchesToScene(bottomIn+heightIn/2),inchesToScene(point.z)],size:[inchesToScene(lengthIn),inchesToScene(heightIn),inchesToScene(Math.max(2,wall.depthIn))],rotationY:-toRadians(wall.rotation),color:wall.color??'#F4F1E9',roughness:.92,metalness:0});}
export function wallSegmentsForOpenings(wall:EditorObject,objects:EditorObject[]):Box3D[]{const boxes:Box3D[]=[],openings=openingsForWall(objects,wall.id).map(opening=>({opening,offset:Math.max(0,Math.min(wall.widthIn-opening.widthIn,openingData(opening).wallOffsetIn??0))})).sort((a,b)=>a.offset-b.offset);if(!openings.length){addWallSegment(boxes,wall,`${wall.id}-full`,0,wall.widthIn,0,wall.heightIn);return boxes;}let cursor=0;openings.forEach(({opening,offset},index)=>{const start=Math.max(cursor,offset),end=Math.min(wall.widthIn,Math.max(start,offset+opening.widthIn));if(start>cursor)addWallSegment(boxes,wall,`${wall.id}-between-${index}`,cursor,start-cursor,0,wall.heightIn);const sill=opening.kind==='window'?Math.max(0,openingData(opening).sillHeightIn??opening.elevationIn??36):0,openingHeight=Math.max(0,Math.min(opening.heightIn,wall.heightIn-sill));if(sill>0)addWallSegment(boxes,wall,`${wall.id}-below-${opening.id}`,start,end-start,0,sill);const top=sill+openingHeight;if(top<wall.heightIn)addWallSegment(boxes,wall,`${wall.id}-above-${opening.id}`,start,end-start,top,wall.heightIn-top);cursor=Math.max(cursor,end);});if(cursor<wall.widthIn)addWallSegment(boxes,wall,`${wall.id}-tail`,cursor,wall.widthIn-cursor,0,wall.heightIn);return boxes;}

function openingPose(opening:EditorObject,objects:EditorObject[]){const data=openingData(opening),wall=data.parentWallId?objects.find(object=>object.id===data.parentWallId&&object.kind==='wall'):undefined;if(!wall)return{x:opening.x+opening.widthIn/2,z:opening.y+opening.depthIn/2,rotation:opening.rotation,sill:opening.kind==='window'?data.sillHeightIn??opening.elevationIn??36:0,depth:opening.depthIn};const offset=Math.max(0,Math.min(wall.widthIn-opening.widthIn,data.wallOffsetIn??0)),point=wallPoint(wall,offset+opening.widthIn/2,wall.depthIn/2);return{x:point.x,z:point.z,rotation:wall.rotation,sill:opening.kind==='window'?data.sillHeightIn??opening.elevationIn??36:0,depth:wall.depthIn};}
function addDoorGeometry(boxes:Box3D[],opening:EditorObject,objects:EditorObject[]){const pose=openingPose(opening,objects),rotation=-toRadians(pose.rotation),x=inchesToScene(pose.x),z=inchesToScene(pose.z),height=inchesToScene(opening.heightIn),trim=2.25;boxes.push({id:opening.id,sourceId:opening.id,kind:'opening',center:[x,height/2,z],size:[inchesToScene(opening.widthIn-1),height,inchesToScene(1.25)],rotationY:rotation,color:'#8A664B',roughness:.52,metalness:.02});boxes.push({id:`${opening.id}-trim-left`,sourceId:opening.id,kind:'trim',center:[x-inchesToScene(opening.widthIn/2+trim/2),height/2,z],size:[inchesToScene(trim),height+inchesToScene(trim),inchesToScene(1.5)],rotationY:rotation,color:'#F0EEE8',roughness:.68,metalness:0},{id:`${opening.id}-trim-right`,sourceId:opening.id,kind:'trim',center:[x+inchesToScene(opening.widthIn/2+trim/2),height/2,z],size:[inchesToScene(trim),height+inchesToScene(trim),inchesToScene(1.5)],rotationY:rotation,color:'#F0EEE8',roughness:.68,metalness:0},{id:`${opening.id}-trim-top`,sourceId:opening.id,kind:'trim',center:[x,height+inchesToScene(trim/2),z],size:[inchesToScene(opening.widthIn+trim*2),inchesToScene(trim),inchesToScene(1.5)],rotationY:rotation,color:'#F0EEE8',roughness:.68,metalness:0});}
function addWindowGeometry(boxes:Box3D[],opening:EditorObject,objects:EditorObject[]){const pose=openingPose(opening,objects),rotation=-toRadians(pose.rotation),x=inchesToScene(pose.x),z=inchesToScene(pose.z),sill=inchesToScene(pose.sill),height=inchesToScene(opening.heightIn);boxes.push({id:opening.id,sourceId:opening.id,kind:'opening',center:[x,sill+height/2,z],size:[inchesToScene(opening.widthIn-1),height,.04],rotationY:rotation,color:'#91C7DC',roughness:.08,metalness:.05},{id:`${opening.id}-sill`,sourceId:opening.id,kind:'trim',center:[x,sill-inchesToScene(.5),z],size:[inchesToScene(opening.widthIn+3),inchesToScene(1),inchesToScene(Math.max(4,pose.depth+1))],rotationY:rotation,color:'#F0EEE8',roughness:.65,metalness:0});}

function countertopBox(boxes:Box3D[],object:EditorObject,x:number,z:number,topY:number,rotation:number,automatic=false){const spec=countertopData(object),material=countertopMaterial(object),width=object.widthIn+spec.overhangSideIn*2,depth=object.depthIn+spec.overhangFrontIn,thickness=spec.thicknessIn;boxes.push({id:automatic?`${object.id}-counter-cap`:object.id,sourceId:object.id,kind:'countertop',center:[x,topY+inchesToScene(thickness/2),z-inchesToScene(spec.overhangFrontIn/2)],size:[inchesToScene(width),inchesToScene(thickness),inchesToScene(depth)],rotationY:rotation,color:material.color,roughness:material.roughness,metalness:material.metalness});if(spec.backsplashHeightIn>0)boxes.push({id:`${object.id}-backsplash`,sourceId:object.id,kind:'countertop',center:[x,topY+inchesToScene(spec.backsplashHeightIn/2),z+inchesToScene(object.depthIn/2-.35)],size:[inchesToScene(width),inchesToScene(spec.backsplashHeightIn),inchesToScene(.7)],rotationY:rotation,color:material.color,roughness:material.roughness,metalness:material.metalness});if(spec.sinkCutout)boxes.push({id:`${object.id}-sink`,sourceId:object.id,kind:'fixture',center:[x,topY-inchesToScene(2.2),z],size:[inchesToScene(Math.min(30,object.widthIn*.55)),inchesToScene(4),inchesToScene(Math.min(20,object.depthIn*.65))],rotationY:rotation,color:'#9AA6A8',roughness:.22,metalness:.8});if(spec.cooktopCutout)boxes.push({id:`${object.id}-cooktop`,sourceId:object.id,kind:'appliance',center:[x,topY+inchesToScene(thickness+.12),z],size:[inchesToScene(Math.min(30,object.widthIn*.5)),inchesToScene(.2),inchesToScene(Math.min(21,object.depthIn*.65))],rotationY:rotation,color:'#252929',roughness:.12,metalness:.55});}
function addIslandDetails(boxes:Box3D[],object:EditorObject,x:number,z:number,baseY:number,rotation:number){const spec=islandData(object),counter=countertopData(object),material=countertopMaterial(object),sideHeight=object.heightIn+counter.thicknessIn;if(spec.waterfallLeft)boxes.push({id:`${object.id}-waterfall-left`,sourceId:object.id,kind:'countertop',center:[x-inchesToScene(object.widthIn/2+counter.overhangSideIn),inchesToScene(sideHeight/2),z],size:[inchesToScene(counter.thicknessIn),inchesToScene(sideHeight),inchesToScene(object.depthIn+counter.overhangFrontIn)],rotationY:rotation,color:material.color,roughness:material.roughness,metalness:material.metalness});if(spec.waterfallRight)boxes.push({id:`${object.id}-waterfall-right`,sourceId:object.id,kind:'countertop',center:[x+inchesToScene(object.widthIn/2+counter.overhangSideIn),inchesToScene(sideHeight/2),z],size:[inchesToScene(counter.thicknessIn),inchesToScene(sideHeight),inchesToScene(object.depthIn+counter.overhangFrontIn)],rotationY:rotation,color:material.color,roughness:material.roughness,metalness:material.metalness});const count=Math.max(0,Math.min(6,Math.round(spec.seatingCount)));for(let i=0;i<count;i++){const spacing=object.widthIn/(count+1),offset=-object.widthIn/2+spacing*(i+1);boxes.push({id:`${object.id}-seat-${i}`,sourceId:object.id,kind:'seating',center:[x+inchesToScene(offset),inchesToScene(16),z+inchesToScene(object.depthIn/2+Math.max(8,spec.seatingOverhangIn*.7))],size:[inchesToScene(14),inchesToScene(32),inchesToScene(14)],rotationY:rotation,color:'#5F5147',roughness:.58,metalness:.05});}if(spec.dishwasher)boxes.push({id:`${object.id}-dishwasher`,sourceId:object.id,kind:'appliance',center:[x+inchesToScene(Math.min(object.widthIn/4,18)),baseY,z-inchesToScene(object.depthIn/2+.4)],size:[inchesToScene(24),inchesToScene(Math.min(34,object.heightIn-2)),.08],rotationY:rotation,color:'#A7ADAE',roughness:.24,metalness:.88});}

function addLightingGeometry(boxes:Box3D[],object:EditorObject){const spec=lightingData(object),x=inchesToScene(object.x+object.widthIn/2),z=inchesToScene(object.y+object.depthIn/2),top=inchesToScene(object.elevationIn??96),glow=kelvinColor(spec.colorTemperatureK),rotation=-toRadians(object.rotation);if(spec.type==='Recessed'){boxes.push({id:object.id,sourceId:object.id,kind:'lighting',center:[x,top,z],size:[inchesToScene(spec.diameterIn),inchesToScene(.8),inchesToScene(spec.diameterIn)],rotationY:rotation,color:'#ECECE8',roughness:.38,metalness:.35},{id:`${object.id}-glow`,sourceId:object.id,kind:'lighting',center:[x,top-inchesToScene(.55),z],size:[inchesToScene(Math.max(2,spec.diameterIn-1)),inchesToScene(.25),inchesToScene(Math.max(2,spec.diameterIn-1))],rotationY:rotation,color:spec.enabled?glow:'#777777',roughness:.05,metalness:0});return;}if(spec.type==='Pendant'){const drop=Math.max(6,spec.dropIn),bottom=top-inchesToScene(drop);boxes.push({id:`${object.id}-canopy`,sourceId:object.id,kind:'lighting',center:[x,top,z],size:[inchesToScene(5),inchesToScene(1),inchesToScene(5)],rotationY:rotation,color:'#343839',roughness:.32,metalness:.82},{id:`${object.id}-stem`,sourceId:object.id,kind:'lighting',center:[x,top-inchesToScene(drop/2),z],size:[inchesToScene(.5),inchesToScene(drop),inchesToScene(.5)],rotationY:rotation,color:'#343839',roughness:.28,metalness:.88},{id:object.id,sourceId:object.id,kind:'lighting',center:[x,bottom,z],size:[inchesToScene(spec.diameterIn),inchesToScene(7),inchesToScene(spec.diameterIn)],rotationY:rotation,color:spec.enabled?glow:'#555555',roughness:.18,metalness:.15});return;}boxes.push({id:object.id,sourceId:object.id,kind:'lighting',center:[x,top,z],size:[inchesToScene(Math.max(6,spec.lengthIn)),inchesToScene(.6),inchesToScene(1.5)],rotationY:rotation,color:spec.enabled?glow:'#777777',roughness:.1,metalness:.08});}

function addHardwareGeometry(boxes:Box3D[],object:EditorObject,x:number,frontZ:number,baseY:number,rotation:number){const geometry=hardwareGeometry(object);if(!geometry)return;const c=Math.cos(rotation),s=Math.sin(rotation);for(const part of geometry.parts){const localX=inchesToScene(part.offsetXIn),localZ=inchesToScene(part.offsetZIn),worldX=x+c*localX+s*localZ,worldZ=frontZ-s*localX+c*localZ;boxes.push({id:`${object.id}-hardware-${part.id}`,sourceId:object.id,kind:'hardware',center:[worldX,baseY+inchesToScene(part.offsetYIn),worldZ],size:[inchesToScene(part.widthIn),inchesToScene(part.heightIn),inchesToScene(part.depthIn)],rotationY:rotation,color:geometry.color,roughness:geometry.roughness,metalness:geometry.metalness});}}

function addCabinetDetails(boxes:Box3D[],object:EditorObject,x:number,z:number,baseY:number,rotation:number){const color=object.color??'#D8D4CA',frontZ=z-inchesToScene(object.depthIn/2+.35),panelHeight=Math.max(8,object.heightIn-3),doubleDoor=object.widthIn>=30,panelWidth=doubleDoor?object.widthIn/2-.16:object.widthIn-.32,centers=doubleDoor?[-object.widthIn/4,object.widthIn/4]:[0];centers.forEach((offset,index)=>boxes.push({id:`${object.id}-door-${index}`,sourceId:object.id,kind:'cabinet-door',center:[x+inchesToScene(offset),baseY,frontZ],size:[inchesToScene(panelWidth),inchesToScene(panelHeight),.035],rotationY:rotation,color:object.kind==='glass-upper'?'#B9D5DD':color,roughness:object.kind==='glass-upper'?.12:.42,metalness:.03}));if(isBaseCabinetKind(object.kind)||object.kind==='island'){const topY=baseY+inchesToScene(object.heightIn/2);countertopBox(boxes,object,x,z,topY,rotation,true);if(object.kind==='island')addIslandDetails(boxes,object,x,z,baseY,rotation);}if(object.kind==='oven-cabinet')boxes.push({id:`${object.id}-oven`,sourceId:object.id,kind:'appliance',center:[x,baseY,z-inchesToScene(object.depthIn/2+.5)],size:[inchesToScene(Math.max(20,object.widthIn-4)),inchesToScene(28),.08],rotationY:rotation,color:'#454A4A',roughness:.2,metalness:.8});if(object.kind==='refrigerator-cabinet')boxes.push({id:`${object.id}-fridge`,sourceId:object.id,kind:'appliance',center:[x,baseY,z-inchesToScene(object.depthIn/2+.45)],size:[inchesToScene(Math.max(28,object.widthIn-3)),inchesToScene(Math.max(60,object.heightIn-10)),.09],rotationY:rotation,color:'#A7ADAE',roughness:.22,metalness:.88});addHardwareGeometry(boxes,object,x,frontZ,baseY,rotation);}

export function buildSceneBoxes(objects:EditorObject[]):Box3D[]{const boxes:Box3D[]=[{id:'floor',kind:'floor',center:[5,-.05,5],size:[16,.1,16],rotationY:0,color:'#D8D2C7',roughness:.76,metalness:0}],toeIds=new Set<string>();continuousToeKickRuns(objects).forEach((run,index)=>{run.ids.forEach(id=>toeIds.add(id));boxes.push({id:`toe-run-${index}`,sourceId:run.ids[0],kind:'toe-kick',center:[inchesToScene(run.x),inchesToScene(run.heightIn/2),inchesToScene(run.y+run.recessIn)],size:[inchesToScene(run.widthIn),inchesToScene(run.heightIn),inchesToScene(Math.max(1,run.depthIn))],rotationY:-toRadians(run.rotation),color:run.color,roughness:.55,metalness:0});});for(const object of objects){if(object.kind==='wall'){boxes.push(...wallSegmentsForOpenings(object,objects));continue;}if(object.kind==='door'){addDoorGeometry(boxes,object,objects);continue;}if(object.kind==='window'){addWindowGeometry(boxes,object,objects);continue;}if(isLighting(object)){addLightingGeometry(boxes,object);continue;}const material=materialFor(object),x=inchesToScene(object.x+object.widthIn/2),z=inchesToScene(object.y+object.depthIn/2),elevation=inchesToScene(object.elevationIn??0),rotation=-toRadians(object.rotation);if(object.kind==='countertop'){countertopBox(boxes,object,x,z,elevation,rotation,false);continue;}const kind:Box3D['kind']=object.kind==='appliance'?'appliance':'cabinet',toeLift=toeIds.has(object.id)&&isBaseLike(object)?(object.toeKick?.heightIn??4):0,baseY=elevation+inchesToScene(object.heightIn/2+toeLift);boxes.push({id:object.id,sourceId:object.id,kind,center:[x,baseY,z],size:[inchesToScene(object.widthIn),inchesToScene(object.heightIn),inchesToScene(object.depthIn)],rotationY:rotation,color:object.color??'#D8D4CA',roughness:material.roughness,metalness:material.metalness});if(isCabinet(object))addCabinetDetails(boxes,object,x,z,baseY,rotation);}return boxes;}
