import { ReactNode, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { HARDWARE_FINISHES, HARDWARE_POSITIONS, HARDWARE_SIZES, HARDWARE_STYLES } from '../domain/catalogs';
import {
  applyHardware,
  CabinetHardware,
  CabinetScope,
  DEFAULT_HARDWARE,
  EditorObject,
  EditorProject,
  isCabinetKind,
  normalizeCabinetHardware,
  removeHardware,
} from '../domain/editor';

type Props={project:EditorProject;selected?:EditorObject;apply:(project:EditorProject)=>void;compact?:boolean};

function Action({label,onPress,active=false,disabled=false}:{label:string;onPress:()=>void;active?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{selected:active,disabled}} disabled={disabled} onPress={onPress} style={[s.action,active&&s.actionActive,disabled&&s.disabled]}><Text style={[s.actionText,active&&s.actionTextActive]}>{label}</Text></Pressable>;}
function Section({title,children}:{title:string;children:ReactNode}){return <View style={s.section}><Text style={s.title}>{title}</Text>{children}</View>;}
function ScopePicker({value,change}:{value:CabinetScope;change:(value:CabinetScope)=>void}){const labels:Record<CabinetScope,string>={selected:'Selected',base:'Base/Tall',wall:'Wall',island:'Island',all:'All'};return <View style={s.wrap}>{(['selected','base','wall','island','all'] as CabinetScope[]).map(item=><Action key={item} label={labels[item]} active={value===item} onPress={()=>change(item)}/>)}</View>;}
function Stepper({label,value,step,min,max,suffix=' in',change,reset,disabled=false}:{label:string;value:number;step:number;min:number;max:number;suffix?:string;change:(value:number)=>void;reset?:()=>void;disabled?:boolean}){const precision=step<1?2:1;const nextValue=(direction:-1|1)=>Math.min(max,Math.max(min,Math.round((value+direction*step)*100)/100));return <View style={[s.stepper,disabled&&s.stepperDisabled]}><Text style={s.label}>{label}</Text><View style={s.stepRow}><Action label="−" disabled={disabled} onPress={()=>change(nextValue(-1))}/><Text style={s.value}>{Number(value.toFixed(precision))}{suffix}</Text><Action label="+" disabled={disabled} onPress={()=>change(nextValue(1))}/>{reset&&<Action label="Reset" disabled={disabled} onPress={reset}/>}</View></View>;}
function FinishTile({item,selected,disabled,onPress}:{item:typeof HARDWARE_FINISHES[number];selected:boolean;disabled:boolean;onPress:()=>void}){const shine=item.metalness>.55,matte=item.roughness>.65;return <Pressable accessibilityRole="button" accessibilityState={{selected,disabled}} disabled={disabled} accessibilityLabel={`${item.displayName} hardware finish`} onPress={onPress} style={[s.finishTile,selected&&s.finishSelected,disabled&&s.disabled]}><View style={[s.finishSwatch,{backgroundColor:item.baseColor}]}>{shine&&<View style={[s.shine,{opacity:Math.max(.1,.58-item.roughness*.42)}]}/>} {matte&&<View style={s.matteOverlay}/>}</View><Text numberOfLines={2} style={s.finishName}>{item.displayName}</Text><Text style={s.finishMeta}>{item.category==='metal'?'Metal':item.category} · {item.roughness<.2?'Polished':item.roughness>.65?'Matte':'Satin'}</Text></Pressable>;}

export function HardwarePanel({project,selected,apply,compact=false}:Props){
  const[scope,setScope]=useState<CabinetScope>('selected');
  const selectedCabinet=selected&&isCabinetKind(selected.kind)?selected:undefined;
  const hardware=useMemo(()=>normalizeCabinetHardware(selectedCabinet?.hardware??DEFAULT_HARDWARE),[selectedCabinet?.hardware]);
  const selectedUnavailable=scope==='selected'&&!selectedCabinet;
  const patch=(value:Partial<CabinetHardware>)=>{if(!selectedUnavailable)apply(applyHardware(project,value,scope));};
  const setCustomSize=(value:number)=>patch({size:'Custom Size',customSizeIn:value});
  const setCustomOffset=(axis:'customOffsetXIn'|'customOffsetYIn',value:number)=>patch({position:'Custom Position',[axis]:value});
  const content=<>
    <Section title="Application"><ScopePicker value={scope} change={setScope}/>{selectedUnavailable&&<Text style={s.warning}>Select a cabinet or choose Base/Tall, Wall, Island or All.</Text>}<Action label="Remove Hardware" disabled={selectedUnavailable} onPress={()=>apply(removeHardware(project,scope))}/></Section>
    <Section title="Style"><View style={s.wrap}>{HARDWARE_STYLES.map(item=><Action key={item} label={item} active={hardware.style===item} disabled={selectedUnavailable} onPress={()=>patch({style:item})}/>)}</View></Section>
    <Section title="Size"><View style={s.wrap}>{HARDWARE_SIZES.map(item=><Action key={item} label={item} active={hardware.size===item} disabled={selectedUnavailable} onPress={()=>patch({size:item})}/>)}</View><Stepper label="Custom Pull Size" value={hardware.customSizeIn??5} step={.25} min={.5} max={36} disabled={selectedUnavailable} change={setCustomSize} reset={()=>patch({size:'Custom Size',customSizeIn:5})}/><Text style={s.help}>Custom size is limited by the selected cabinet door. Vertical pulls use the cabinet height instead of its width.</Text></Section>
    <Section title="Finish"><View style={s.finishGrid}>{HARDWARE_FINISHES.map(item=><FinishTile key={item.id} item={item} selected={hardware.finishId===item.id} disabled={selectedUnavailable} onPress={()=>patch({finishId:item.id})}/>)}</View></Section>
    <Section title="Position"><View style={s.wrap}>{HARDWARE_POSITIONS.map(item=><Action key={item} label={item} active={hardware.position===item} disabled={selectedUnavailable} onPress={()=>patch({position:item})}/>)}</View><View style={s.customPosition}><Stepper label="Custom Horizontal Offset" value={hardware.customOffsetXIn??0} step={.5} min={-96} max={96} disabled={selectedUnavailable} change={value=>setCustomOffset('customOffsetXIn',value)} reset={()=>setCustomOffset('customOffsetXIn',0)}/><Stepper label="Custom Vertical Offset" value={hardware.customOffsetYIn??0} step={.5} min={-96} max={96} disabled={selectedUnavailable} change={value=>setCustomOffset('customOffsetYIn',value)} reset={()=>setCustomOffset('customOffsetYIn',0)}/></View><Text style={s.help}>Offsets are measured from the center of the cabinet front. Kitchen AI clamps hardware inside the usable door area so it does not float outside the cabinet.</Text></Section>
    <View style={s.summary}><Text style={s.summaryTitle}>Current Hardware</Text><Text style={s.summaryText}>{hardware.style} · {hardware.size==='Custom Size'?`${hardware.customSizeIn??5} in`:hardware.size} · {HARDWARE_FINISHES.find(item=>item.id===hardware.finishId)?.displayName??hardware.finishId}</Text><Text style={s.summaryText}>{hardware.position}{hardware.position==='Custom Position'?` · X ${hardware.customOffsetXIn??0} in · Y ${hardware.customOffsetYIn??0} in`:''}</Text></View>
  </>;
  if(compact)return <View style={[s.panel,s.compactPanel]}>{content}</View>;
  return <ScrollView contentContainerStyle={s.panel} keyboardShouldPersistTaps="handled">{content}</ScrollView>;
}

const s=StyleSheet.create({panel:{paddingBottom:26},compactPanel:{paddingBottom:8},section:{gap:8,marginBottom:18},title:{fontSize:14,fontWeight:'900',color:'#1D2A27',textTransform:'uppercase'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:4},action:{minHeight:42,borderWidth:1,borderColor:'#B8C5C1',borderRadius:8,backgroundColor:'#fff',paddingHorizontal:10,alignItems:'center',justifyContent:'center',marginBottom:4},actionActive:{backgroundColor:'#DDEEE8',borderColor:'#5A917F'},actionText:{fontSize:12,fontWeight:'800',color:'#263530'},actionTextActive:{color:'#0E4939'},disabled:{opacity:.35},warning:{fontSize:12,lineHeight:18,color:'#8A4F38',backgroundColor:'#FFF0E9',borderRadius:7,padding:8},stepper:{gap:5,marginTop:4},stepperDisabled:{opacity:.55},label:{fontSize:12,fontWeight:'800',color:'#43524D'},stepRow:{flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:4},value:{minWidth:78,textAlign:'center',fontSize:13,fontWeight:'900',color:'#263530'},help:{fontSize:11,lineHeight:17,color:'#62716B'},finishGrid:{flexDirection:'row',flexWrap:'wrap',gap:6},finishTile:{width:'31%',minHeight:94,borderWidth:2,borderColor:'transparent',borderRadius:9,backgroundColor:'#fff',padding:4},finishSelected:{borderColor:'#315F55',backgroundColor:'#E4F0EC'},finishSwatch:{height:42,borderRadius:6,borderWidth:1,borderColor:'#B9C3BF',overflow:'hidden'},shine:{position:'absolute',top:-8,bottom:-8,left:'38%',width:'18%',backgroundColor:'#FFFFFF',transform:[{rotate:'18deg'}]},matteOverlay:{...StyleSheet.absoluteFillObject,backgroundColor:'#FFFFFF',opacity:.07},finishName:{fontSize:9,fontWeight:'800',color:'#2B3935',marginTop:4},finishMeta:{fontSize:8,fontWeight:'700',color:'#71807A',textTransform:'capitalize'},customPosition:{gap:8},summary:{borderWidth:1,borderColor:'#B9C8C3',borderRadius:10,backgroundColor:'#EEF5F2',padding:10,gap:4},summaryTitle:{fontSize:12,fontWeight:'900',color:'#21483D',textTransform:'uppercase'},summaryText:{fontSize:11,lineHeight:17,fontWeight:'700',color:'#42534D'}});
