import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { EditorObject, EditorProject } from '../domain/editor';
import { COLOR_TEMPERATURES, createLighting, isLighting, kelvinColor, lightingData, LightingType, updateLighting } from '../domain/lighting';

type Props={project:EditorProject;selected?:EditorObject;apply:(project:EditorProject)=>void;compact?:boolean};
const TYPES:LightingType[]=['Recessed','Pendant','Under Cabinet'];
function Button({label,onPress,active=false}:{label:string;onPress:()=>void;active?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{selected:active}} onPress={onPress} style={[s.button,active&&s.active]}><Text style={[s.buttonText,active&&s.activeText]}>{label}</Text></Pressable>;}
function Stepper({label,value,suffix='',onChange,min=0,max=100}:{label:string;value:number;suffix?:string;onChange:(value:number)=>void;min?:number;max?:number}){return <View style={s.field}><Text style={s.label}>{label}</Text><View style={s.row}><Button label="−" onPress={()=>onChange(Math.max(min,value-1))}/><Text style={s.value}>{Math.round(value*10)/10}{suffix}</Text><Button label="+" onPress={()=>onChange(Math.min(max,value+1))}/></View></View>;}
export function LightingPanel({project,selected,apply,compact=false}:Props){const light=selected&&isLighting(selected)?selected:undefined,spec=light?lightingData(light):undefined;const add=(type:LightingType)=>{const object=createLighting(type,{x:180+project.objects.length*8,y:140+project.objects.length*6});apply({...project,objects:[...project.objects,object],selectedId:object.id});};return <ScrollView>{!compact&&<><Text style={s.title}>Lighting</Text><Text style={s.help}>Add kitchen lighting and edit color temperature, intensity and fixture dimensions.</Text><View style={s.grid}>{TYPES.map(type=><Button key={type} label={`Add ${type}`} onPress={()=>add(type)}/>)}</View></>}{light&&spec&&<><Text style={s.section}>Selected Fixture</Text><View style={s.row}>{TYPES.map(type=><Button key={type} label={type} active={spec.type===type} onPress={()=>apply(updateLighting(project,light.id,{type}))}/>)}</View><Text style={s.section}>Color Temperature</Text><View style={s.grid}>{COLOR_TEMPERATURES.map(k=><Pressable accessibilityRole="button" accessibilityState={{selected:spec.colorTemperatureK===k}} key={k} onPress={()=>apply(updateLighting(project,light.id,{colorTemperatureK:k}))} style={[s.temp,spec.colorTemperatureK===k&&s.tempActive]}><View style={[s.tempDot,{backgroundColor:kelvinColor(k)}]}/><Text style={s.tempText}>{k}K</Text></Pressable>)}</View><Stepper label="Intensity" value={spec.intensityPercent} suffix="%" min={0} max={100} onChange={value=>apply(updateLighting(project,light.id,{intensityPercent:value}))}/>{spec.type!=='Under Cabinet'&&<Stepper label="Diameter" value={spec.diameterIn} suffix=" in" min={2} max={30} onChange={value=>apply(updateLighting(project,light.id,{diameterIn:value}))}/>} {spec.type==='Pendant'&&<Stepper label="Drop" value={spec.dropIn} suffix=" in" min={6} max={72} onChange={value=>apply(updateLighting(project,light.id,{dropIn:value}))}/>} {spec.type==='Under Cabinet'&&<Stepper label="Length" value={spec.lengthIn} suffix=" in" min={6} max={96} onChange={value=>apply(updateLighting(project,light.id,{lengthIn:value}))}/>}<Button label={spec.enabled?'Light On':'Light Off'} active={spec.enabled} onPress={()=>apply(updateLighting(project,light.id,{enabled:!spec.enabled}))}/></>}</ScrollView>;}
const s=StyleSheet.create({title:{fontSize:15,fontWeight:'900',color:'#1D2A27',textTransform:'uppercase',marginBottom:7},section:{fontSize:12,fontWeight:'900',color:'#43524D',textTransform:'uppercase',marginTop:16,marginBottom:7},help:{fontSize:13,lineHeight:19,color:'#5C6B66',marginBottom:10},row:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:4},grid:{flexDirection:'row',flexWrap:'wrap',gap:5},button:{minHeight:40,borderWidth:1,borderColor:'#B8C5C1',borderRadius:8,backgroundColor:'#fff',paddingHorizontal:10,alignItems:'center',justifyContent:'center',marginBottom:4},active:{backgroundColor:'#DDEEE8',borderColor:'#5A917F'},buttonText:{fontSize:12,fontWeight:'800',color:'#263530'},activeText:{color:'#0E4939'},field:{gap:5,marginTop:10},label:{fontSize:12,fontWeight:'800',color:'#43524D'},value:{minWidth:72,textAlign:'center',fontSize:13,fontWeight:'900',color:'#263530'},temp:{width:'30%',minHeight:60,borderWidth:1,borderColor:'#C6D0CD',borderRadius:8,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},tempActive:{borderWidth:2,borderColor:'#315F55',backgroundColor:'#E4F0EC'},tempDot:{width:24,height:24,borderRadius:12,borderWidth:1,borderColor:'#B7B7B0'},tempText:{fontSize:10,fontWeight:'800',marginTop:3,color:'#36443F'}});
