import { useEffect, useMemo, useRef } from 'react';
import { EditorProject } from '../domain/editor';
import { buildSceneBoxes } from '../domain/geometry';

type Mat4=number[];
function multiply(a:Mat4,b:Mat4):Mat4{const out=new Array(16).fill(0);for(let r=0;r<4;r++)for(let c=0;c<4;c++)for(let k=0;k<4;k++)out[r*4+c]+=a[r*4+k]*b[k*4+c];return out;}
function perspective(fov:number,aspect:number,near:number,far:number):Mat4{const f=1/Math.tan(fov/2),nf=1/(near-far);return[f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0];}
function normalize(v:number[]){const length=Math.hypot(v[0],v[1],v[2])||1;return v.map(value=>value/length);}
function cross(a:number[],b:number[]){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}
function lookAt(eye:number[],target:number[],up=[0,1,0]):Mat4{const z=normalize([eye[0]-target[0],eye[1]-target[1],eye[2]-target[2]]),x=normalize(cross(up,z)),y=cross(z,x);return[x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-(x[0]*eye[0]+x[1]*eye[1]+x[2]*eye[2]),-(y[0]*eye[0]+y[1]*eye[1]+y[2]*eye[2]),-(z[0]*eye[0]+z[1]*eye[1]+z[2]*eye[2]),1];}
const translate=(x:number,y:number,z:number):Mat4=>[1,0,0,0,0,1,0,0,0,0,1,0,x,y,z,1];
const scale=(x:number,y:number,z:number):Mat4=>[x,0,0,0,0,y,0,0,0,0,z,0,0,0,0,1];
function rotateY(angle:number):Mat4{const c=Math.cos(angle),s=Math.sin(angle);return[c,0,-s,0,0,1,0,0,s,0,c,0,0,0,0,1];}
function transformPoint(m:Mat4,p:number[]){return[m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13],m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14],m[3]*p[0]+m[7]*p[1]+m[11]*p[2]+m[15]];}
function colorToRgb(value:string){const short=value.replace('#',''),full=short.length===3?short.split('').map(x=>x+x).join(''):short,n=parseInt(full,16)||0xcccccc;return[((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255];}
const VERTEX_SHADER=`attribute vec3 aPosition;attribute vec3 aNormal;uniform mat4 uModel;uniform mat4 uViewProjection;varying vec3 vNormal;varying vec3 vWorld;void main(){vec4 world=uModel*vec4(aPosition,1.0);vWorld=world.xyz;vNormal=mat3(uModel)*aNormal;gl_Position=uViewProjection*world;}`;
const FRAGMENT_SHADER=`precision mediump float;varying vec3 vNormal;varying vec3 vWorld;uniform vec3 uColor;uniform float uMetalness;uniform float uRoughness;uniform vec3 uEye;void main(){vec3 N=normalize(vNormal);vec3 L=normalize(vec3(-0.35,0.9,0.45));vec3 V=normalize(uEye-vWorld);vec3 H=normalize(L+V);float diffuse=max(dot(N,L),0.0);float specular=pow(max(dot(N,H),0.0),mix(90.0,10.0,uRoughness));vec3 base=uColor*(0.28+0.72*diffuse);vec3 reflection=mix(vec3(0.65),uColor,uMetalness);gl_FragColor=vec4(base+reflection*specular*(0.15+0.7*uMetalness),1.0);}`;
const CUBE=new Float32Array([-0.5,-0.5,0.5,0,0,1,0.5,-0.5,0.5,0,0,1,0.5,0.5,0.5,0,0,1,-0.5,-0.5,0.5,0,0,1,0.5,0.5,0.5,0,0,1,-0.5,0.5,0.5,0,0,1,0.5,-0.5,-0.5,0,0,-1,-0.5,-0.5,-0.5,0,0,-1,-0.5,0.5,-0.5,0,0,-1,0.5,-0.5,-0.5,0,0,-1,-0.5,0.5,-0.5,0,0,-1,0.5,0.5,-0.5,0,0,-1,-0.5,-0.5,-0.5,-1,0,0,-0.5,-0.5,0.5,-1,0,0,-0.5,0.5,0.5,-1,0,0,-0.5,-0.5,-0.5,-1,0,0,-0.5,0.5,0.5,-1,0,0,-0.5,0.5,-0.5,-1,0,0,0.5,-0.5,0.5,1,0,0,0.5,-0.5,-0.5,1,0,0,0.5,0.5,-0.5,1,0,0,0.5,-0.5,0.5,1,0,0,0.5,0.5,-0.5,1,0,0,0.5,0.5,0.5,1,0,0,-0.5,0.5,0.5,0,1,0,0.5,0.5,0.5,0,1,0,0.5,0.5,-0.5,0,1,0,-0.5,0.5,0.5,0,1,0,0.5,0.5,-0.5,0,1,0,-0.5,0.5,-0.5,0,1,0,-0.5,-0.5,-0.5,0,-1,0,0.5,-0.5,-0.5,0,-1,0,0.5,-0.5,0.5,0,-1,0,-0.5,-0.5,-0.5,0,-1,0,0.5,-0.5,0.5,0,-1,0,-0.5,-0.5,0.5,0,-1,0]);
function compileShader(gl:WebGLRenderingContext,type:number,source:string){const shader=gl.createShader(type)!;gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(shader)??'Shader compile error');return shader;}
function createProgram(gl:WebGLRenderingContext){const program=gl.createProgram()!;gl.attachShader(program,compileShader(gl,gl.VERTEX_SHADER,VERTEX_SHADER));gl.attachShader(program,compileShader(gl,gl.FRAGMENT_SHADER,FRAGMENT_SHADER));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program)??'Shader link error');return program;}

export function WebGLViewport({project,preview}:{project:EditorProject;preview:(project:EditorProject)=>void}){
  const canvasRef=useRef<HTMLCanvasElement|null>(null),hits=useRef(new Map<string,{x:number;y:number}>()),drag=useRef({x:0,y:0,yaw:0,pitch:0,tx:0,ty:0,mode:'orbit' as 'orbit'|'pan',active:false,moved:false});
  const boxes=useMemo(()=>buildSceneBoxes(project.objects),[project.objects]);
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)return;let program:WebGLProgram;try{program=createProgram(gl);}catch{return;}const buffer=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,CUBE,gl.STATIC_DRAW);gl.useProgram(program);const position=gl.getAttribLocation(program,'aPosition'),normal=gl.getAttribLocation(program,'aNormal');gl.enableVertexAttribArray(position);gl.enableVertexAttribArray(normal);gl.vertexAttribPointer(position,3,gl.FLOAT,false,24,0);gl.vertexAttribPointer(normal,3,gl.FLOAT,false,24,12);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);const modelLocation=gl.getUniformLocation(program,'uModel'),vpLocation=gl.getUniformLocation(program,'uViewProjection'),colorLocation=gl.getUniformLocation(program,'uColor'),roughLocation=gl.getUniformLocation(program,'uRoughness'),metalLocation=gl.getUniformLocation(program,'uMetalness'),eyeLocation=gl.getUniformLocation(program,'uEye'),dpr=Math.min(window.devicePixelRatio||1,2),width=Math.max(1,canvas.clientWidth),height=Math.max(1,canvas.clientHeight);canvas.width=Math.floor(width*dpr);canvas.height=Math.floor(height*dpr);gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.88,.9,.89,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const yaw=project.camera3d.yaw*Math.PI/180,pitch=project.camera3d.pitch*Math.PI/180,distance=project.camera3d.distance/42,target=[project.camera3d.target.x/24,2,project.camera3d.target.y/24],eye=[target[0]+Math.cos(pitch)*Math.sin(yaw)*distance,target[1]+Math.sin(pitch)*distance,target[2]+Math.cos(pitch)*Math.cos(yaw)*distance],vp=multiply(perspective(Math.PI/4,canvas.width/canvas.height,.05,100),lookAt(eye,target));gl.uniformMatrix4fv(vpLocation,false,new Float32Array(vp));gl.uniform3fv(eyeLocation,new Float32Array(eye));hits.current.clear();for(const box of boxes){const model=multiply(translate(...box.center),multiply(rotateY(box.rotationY),scale(...box.size)));gl.uniformMatrix4fv(modelLocation,false,new Float32Array(model));gl.uniform3fv(colorLocation,new Float32Array(colorToRgb(box.sourceId===project.selectedId?'#49A88B':box.color)));gl.uniform1f(roughLocation,box.roughness);gl.uniform1f(metalLocation,box.metalness);gl.drawArrays(gl.TRIANGLES,0,36);if(box.sourceId&&!hits.current.has(box.sourceId)){const p=transformPoint(vp,box.center);if(p[3]>0)hits.current.set(box.sourceId,{x:(p[0]/p[3]*.5+.5)*width,y:(1-(p[1]/p[3]*.5+.5))*height});}}return()=>{gl.deleteBuffer(buffer);gl.deleteProgram(program);};},[boxes,project.camera3d,project.selectedId]);
  const pick=(event:any)=>{const rect=event.currentTarget.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top;let id:string|undefined,best=44;for(const[candidate,p]of hits.current){const distance=Math.hypot(p.x-x,p.y-y);if(distance<best){best=distance;id=candidate;}}return id;};
  return <canvas ref={canvasRef} aria-label="3D kitchen viewport" style={{width:'100%',height:'100%',display:'block',cursor:drag.current.active?'grabbing':'grab'}} onContextMenu={event=>event.preventDefault()} onWheel={event=>{event.preventDefault();preview({...project,camera3d:{...project.camera3d,distance:Math.max(180,Math.min(1100,project.camera3d.distance+(event.deltaY>0?32:-32)))}});}} onMouseDown={event=>{drag.current={x:event.clientX,y:event.clientY,yaw:project.camera3d.yaw,pitch:project.camera3d.pitch,tx:project.camera3d.target.x,ty:project.camera3d.target.y,mode:event.button===1||event.button===2?'pan':'orbit',active:true,moved:false};}} onMouseMove={event=>{if(!drag.current.active)return;const dx=event.clientX-drag.current.x,dy=event.clientY-drag.current.y;if(Math.abs(dx)+Math.abs(dy)>3)drag.current.moved=true;if(drag.current.mode==='orbit')preview({...project,camera3d:{...project.camera3d,yaw:drag.current.yaw+dx*.28,pitch:Math.max(8,Math.min(78,drag.current.pitch+dy*.2))}});else preview({...project,camera3d:{...project.camera3d,target:{x:drag.current.tx-dx*.45,y:drag.current.ty+dy*.45}}});}} onMouseUp={event=>{drag.current.active=false;if(!drag.current.moved)preview({...project,selectedId:pick(event)});}} onMouseLeave={()=>{drag.current.active=false;}} onDoubleClick={event=>{const id=pick(event),object=project.objects.find(item=>item.id===id);if(object)preview({...project,selectedId:object.id,camera3d:{...project.camera3d,target:{x:object.x+object.widthIn/2,y:object.y+object.depthIn/2},distance:Math.max(260,project.camera3d.distance*.72)}});}}/>;
}
