import { useRef } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { clampZoom, EditorProject } from '../domain/editor';
import { createObjectDragOrigin, moveObjectByPlanDelta, OBJECT_SNAP_IN, ObjectDragOrigin } from '../domain/objectMovement';

const AnyView=View as any;
const AnyPressable=Pressable as any;
type DragState={id:string;x:number;y:number;active:boolean;moved:boolean;origin?:ObjectDragOrigin;start?:EditorProject};
const PLAN_SCALE=.45;
const GRID_IN=12;
const formatInches=(value:number)=>{const feet=Math.floor(value/12),inches=Math.round((value-feet*12)*10)/10;return feet>0?`${feet}' ${inches>0?`${inches}\"`:''}`:`${inches}\"`;};

export function Workspace2D({project,preview,commitHistory}:{project:EditorProject;preview:(project:EditorProject)=>void;commitHistory:(snapshot:EditorProject,finalProject:EditorProject)=>void}){
  const pan=useRef({x:0,y:0,panX:0,panY:0,active:false});
  const move=useRef<DragState>({id:'',x:0,y:0,active:false,moved:false});
  const spaceHeld=useRef(false);
  const finishMove=()=>{const state=move.current;if(state.active&&state.moved&&state.start)commitHistory(state.start,project);move.current={id:'',x:0,y:0,active:false,moved:false};};
  const webProps={tabIndex:0,onKeyDown:(event:any)=>{if(event.code==='Space'){spaceHeld.current=true;event.preventDefault();}},onKeyUp:(event:any)=>{if(event.code==='Space')spaceHeld.current=false;},onBlur:()=>{spaceHeld.current=false;pan.current.active=false;finishMove();},onWheel:(event:any)=>{event.preventDefault();const old=project.view2d.zoom,next=clampZoom(old+(event.deltaY<0?.08:-.08));if(next===old)return;const rect=event.currentTarget.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top,ratio=next/old;preview({...project,view2d:{...project.view2d,zoom:next,pan:{x:x-(x-project.view2d.pan.x)*ratio,y:y-(y-project.view2d.pan.y)*ratio}}});},onMouseDown:(event:any)=>{if(event.button===1||(event.button===0&&spaceHeld.current)){pan.current={x:event.clientX,y:event.clientY,panX:project.view2d.pan.x,panY:project.view2d.pan.y,active:true};event.preventDefault();}},onMouseMove:(event:any)=>{if(pan.current.active){preview({...project,view2d:{...project.view2d,pan:{x:pan.current.panX+event.clientX-pan.current.x,y:pan.current.panY+event.clientY-pan.current.y}}});return;}if(!move.current.active||!move.current.origin)return;const dx=(event.clientX-move.current.x)/project.view2d.zoom,dy=(event.clientY-move.current.y)/project.view2d.zoom;if(Math.abs(dx)+Math.abs(dy)>.5)move.current.moved=true;preview(moveObjectByPlanDelta(project,move.current.origin,dx,dy));},onMouseUp:()=>{pan.current.active=false;finishMove();},onMouseLeave:()=>{pan.current.active=false;finishMove();},onContextMenu:(event:any)=>event.preventDefault()};
  const gridStyle=project.view2d.grid?({backgroundImage:'linear-gradient(to right, rgba(69,92,84,.14) 1px, transparent 1px), linear-gradient(to bottom, rgba(69,92,84,.14) 1px, transparent 1px)',backgroundSize:`${GRID_IN*PLAN_SCALE}px ${GRID_IN*PLAN_SCALE}px`} as any):undefined;
  return <AnyView accessibilityLabel="2D kitchen workspace" style={[s.workspace,gridStyle]} {...webProps} onClick={(event:any)=>{if(event.target===event.currentTarget)preview({...project,selectedId:undefined});}}><View style={[s.plan,{transform:[{translateX:project.view2d.pan.x},{translateY:project.view2d.pan.y},{scale:project.view2d.zoom}]}]}>{project.objects.map(object=>{const width=Math.max(10,object.widthIn*PLAN_SCALE),depth=object.kind==='wall'?Math.max(4,object.depthIn*PLAN_SCALE):Math.max(8,object.depthIn*PLAN_SCALE);return <AnyPressable key={object.id} accessibilityRole="button" accessibilityLabel={`${object.name}, ${formatInches(object.widthIn)} by ${formatInches(object.depthIn)}`} onPress={()=>preview({...project,selectedId:object.id})} onMouseDown={(event:any)=>{if(event.button!==0||spaceHeld.current)return;event.stopPropagation();move.current={id:object.id,x:event.clientX,y:event.clientY,origin:createObjectDragOrigin(project,object.id),active:true,moved:false,start:project};preview({...project,selectedId:object.id});}} style={[s.object,{left:object.x,top:object.y,width,height:depth,backgroundColor:object.color??(object.kind==='window'?'#91C7DC':object.kind==='door'?'#8A664B':'#C7CECA'),transform:[{rotate:`${object.rotation}deg`}]},project.selectedId===object.id&&s.selected]}><Text numberOfLines={1} style={s.label}>{object.name}</Text>{project.view2d.measurements&&<View pointerEvents="none" style={[s.measureWrap,{top:depth+4,minWidth:Math.max(72,width)}]}><View style={s.dimensionLine}/><Text style={s.measureText}>{object.kind==='wall'?formatInches(object.widthIn):`${formatInches(object.widthIn)} × ${formatInches(object.depthIn)}`}</Text></View>}</AnyPressable>;})}</View>{project.view2d.grid&&<View pointerEvents="none" style={s.scaleBadge}><Text style={s.scaleText}>Grid 12 in · Snap {project.view2d.snap?`${OBJECT_SNAP_IN} in`:'Off'}</Text></View>}</AnyView>;
}
const s=StyleSheet.create({workspace:{flex:1,overflow:'hidden',backgroundColor:'#E2E7E5'},plan:{position:'absolute',left:0,top:0,width:900,height:650},object:{position:'absolute',borderWidth:1,borderColor:'#596762',borderRadius:3,justifyContent:'center'},label:{fontSize:9,fontWeight:'700',paddingHorizontal:2},selected:{borderWidth:3,borderColor:'#0B785A'},measureWrap:{position:'absolute',left:0,alignItems:'center'},dimensionLine:{height:1,width:'100%',backgroundColor:'#315F55'},measureText:{fontSize:9,fontWeight:'900',color:'#24453C',backgroundColor:'rgba(244,248,246,.92)',paddingHorizontal:4,paddingVertical:2,borderRadius:3,marginTop:2},scaleBadge:{position:'absolute',right:12,bottom:12,backgroundColor:'rgba(23,33,31,.88)',paddingHorizontal:9,paddingVertical:6,borderRadius:6},scaleText:{fontSize:10,fontWeight:'800',color:'#E7F0ED'}});
